### PR TITLE
Feature/issue115

### PR DESCRIPTION
**Pull request by Odyno**
This commit respect the issue 115 ( http://code.google.com/p/mixare/issues/detail?id=115&sort=-id&colspec=ID%20Type%20Status%20Priority%20Stars%20Version%20Owner%20Summary )

This commit  propose:
A) Isolation MixContext variable and protect it to thread race condition.
B) Change MixContext  to pseudo-factory of Managers. 
C) Any managers have own personal package. Any manger use package scope tecnique. Applied factory-pattern on any managers (I think it's good for every future change of implementation or platform)
D) DonwloadManager now use structure thread safe.
E) Documented public class

I have test it on my device, and I don't have regression ( I think it's a bit faster )

### CODE REVIEW

**Comment by danielegobbetti** [comment]
Really cool contribution! Thanks a lot.

If you can, I'd ask you to rebase the pull request against the current status of the development branch. Otherwise I'll proceed with cherry-picking your commits.

Thanks again,
Daniele

**Comment by Odyno** [comment]
what does it mean "rebase the pull request against"? I'm a nerd with git-flow (and English :-)

Tell me if I understood:

odyssey@Itaca:/devel/MixareWorkspace/mixare$ git branch -a

development
- feature/Issue115

master

remotes/origin/HEAD -> origin/master

remotes/origin/development

remotes/origin/feature/Issue115

remotes/origin/feature/issue101

remotes/origin/master

remotes/origin/upstream/mapmerge

remotes/upstream/development

remotes/upstream/feature/issue101

remotes/upstream/master

remotes/upstream/upstream/mapmerge

odyssey@Itaca:/devel/MixareWorkspace/mixare$ git fetch upstream

[...]
odyssey@Itaca:/devel/MixareWorkspace/mixare$ git merge upstream/development

[...]

is it right?

**Comment by Odyno** [comment]
is it ok?

**Comment by danielegobbetti** [comment]
Yes it looks good now! thanks

**Pull request merged**
